version: '3.3'

services:

  test:
    container_name: pipeline-test
    build: .
    environment:
      - AWS_ENVIRONMENT=staging
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test.com
    command: >
      py.test --pep8
              --ignore=W503
              --black
              --flakes
              --mccabe
              --cov=src
              --cov-report=term-missing
              --junitxml=/tmp/test-results.xml
              -vv

  deploy:
    container_name: pipeline-deploy
    build: .
    environment:
      - AWS_ENVIRONMENT=staging
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SLS_DEBUG
    command: sls deploy --region-eu-west-1
