version: '3.7'

services:

  test:
    container_name: pipeline-test
    build: .
    environment:
      - AWS_ENVIRONMENT=staging
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOG_LEVEL=DEBUG
    command: >
      py.test --pep8
              --ignore=W503
              --black
              --flakes
              --mccabe
              --cov=lib
              --cov-report=term-missing
              --junitxml=/tmp/test-results.xml
              -vv
